// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfmohkagbwkeaimnmlqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmbW9oa2FnYndrZWFpbW5tbHFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMzUyMTIsImV4cCI6MjA2MDgxMTIxMn0.vJWUpUWi_GehIpSYXzJXH4qLJUj9rLoOJhB7s-quIDs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);